from collections.abc import Iterable, Sequence
from typing import Protocol, overload


class Frame(Protocol):
    """The slice of the pandas frame surface the fit lane touches, mockable without pandas."""

    @overload
    def __getitem__(self, key: str) -> Sequence[float]: ...

    @overload
    def __getitem__(self, key: list[str]) -> Frame: ...

    def __getitem__(self, key: str | list[str]) -> Sequence[float] | Frame: ...

    def __len__(self) -> int: ...

    @property
    def columns(self) -> Iterable[str]: ...

    @property
    def index(self) -> Iterable[int]: ...

    def drop(self, index: Iterable[int]) -> Frame: ...

    def nlargest(self, count: int, column: str) -> Frame: ...

    def sample(self, *, n: int, random_state: int) -> Frame: ...
