import json
from collections.abc import Sequence
from pathlib import Path
from typing import ClassVar

from ..graph.category import Category
from ..graph.node import Node


class LedgerIndex:
    """The generated workspace index: one markdown table and one graph JSON beside it.

    Both artifacts regenerate from node state alone, so the committed index can
    never silently drift from the ledger: `doctor` fails when a regeneration
    would change either file. Hand-authored prose is never deleted; the first
    generation over a hand-written index moves its whole body under the manual
    section, which every later regeneration preserves verbatim.
    """

    MARK: ClassVar[str] = (
        "<!-- generated by `atpx index` from node.md state; "
        "regenerate instead of editing anything above the manual section -->"
    )
    MANUAL: ClassVar[str] = "## Manual    (hand-authored, preserved verbatim)"

    def __init__(self, path: Path) -> None:
        """path: the index markdown file the workspace manifest declares."""
        self.path = path

    @property
    def graph_path(self) -> Path:
        """The graph JSON artifact, beside the index note."""
        return self.path.with_suffix(".json")

    def claim(self, node: Node) -> str:
        """One node's one-line claim, its `summary` or its statement heading."""
        return node.summary or node.headline

    def graph(self, nodes: Sequence[Node]) -> dict[str, list[dict[str, str]]]:
        """The blueprint-shaped graph: nodes with slug, state, and claim; edges from depends."""
        ordered = sorted(nodes, key=lambda node: node.name)
        rows = [
            {"slug": node.name, "state": self.state(node), "claim": self.claim(node)}
            for node in ordered
        ]
        edges = [
            {"from": node.name, "to": dependency}
            for node in ordered
            for dependency in node.front.depends
        ]
        return {"nodes": rows, "edges": edges}

    def render(self, nodes: Sequence[Node]) -> str:
        """The full regenerated index text, manual prose preserved.

        nodes: every blueprint node the store tracks.
        """
        title, manual = self.surroundings()
        blocks = [f"# {title}", self.MARK, self.table(nodes)]
        if manual:
            blocks.append(f"{self.MANUAL}\n\n{manual}")
        return "\n\n".join(blocks) + "\n"

    def rendered_graph(self, nodes: Sequence[Node]) -> str:
        """The graph JSON artifact's exact text."""
        return json.dumps(self.graph(nodes), indent=2) + "\n"

    def stale(self, nodes: Sequence[Node]) -> list[Path]:
        """The artifacts a regeneration would change, empty when the index is current."""
        expected = {
            self.path: self.render(nodes),
            self.graph_path: self.rendered_graph(nodes),
        }
        return [
            path
            for path, text in expected.items()
            if not path.exists() or path.read_text() != text
        ]

    def state(self, node: Node) -> str:
        """One node's index state: its raw status, or its kind for a statusless special node."""
        special = node.front.category is not Category.CLAIM
        return node.raw_status or (node.front.kind or "" if special else "")

    def surroundings(self) -> tuple[str, str]:
        """The (title, manual prose) the regeneration preserves from the existing file.

        A file this generator wrote keeps its title and whatever sits under the
        manual heading. A hand-authored file donates its first `# ` heading as
        the title and its entire remaining body as the manual prose, so the
        first generation moves hand-written sections instead of deleting them.
        """
        if not self.path.exists():
            return self.path.stem, ""
        text = self.path.read_text()
        lines = text.splitlines()
        title = next(
            (line.removeprefix("# ") for line in lines if line.startswith("# ")), self.path.stem
        )
        if self.MARK in text:
            return title, text.partition(self.MANUAL)[2].strip()
        body = [line for line in lines if line != f"# {title}"]
        return title, "\n".join(body).strip()

    def table(self, nodes: Sequence[Node]) -> str:
        """The generated nodes table, one row per node sorted by slug."""
        rows = [
            f"| [[{node.name}]] | {self.__cell(self.state(node))} "
            f"| {self.__cell(self.claim(node))} |"
            for node in sorted(nodes, key=lambda node: node.name)
        ]
        return "\n".join(["| Node | State | Claim |", "| --- | --- | --- |", *rows])

    def write(self, nodes: Sequence[Node]) -> str:
        """Write both artifacts, returning the index markdown.

        nodes: every blueprint node the store tracks.
        """
        text = self.render(nodes)
        self.path.parent.mkdir(parents=True, exist_ok=True)
        self.path.write_text(text)
        self.graph_path.write_text(self.rendered_graph(nodes))
        return text

    @staticmethod
    def __cell(text: str) -> str:
        """One table cell's text, pipes escaped so a claim can never break the row."""
        return text.replace("|", "\\|")
