import json
import os
from collections.abc import Sequence
from functools import cached_property
from pathlib import Path, PurePath
from typing import ClassVar

from ..core.locking import Guard
from ..graph.aliasing import Aliases
from ..graph.category import Category
from ..graph.node import Node
from ..graph.status import Status
from .exceptions import BlankIndexError

_UNSTATED = "unstated"


class LedgerIndex:
    """The generated workspace index: an Open Knowledge Format note and a graph JSON beside it.

    The note is what the format calls an index, a section per state with one bullet per
    node, and it carries no frontmatter at all unless the workspace declares itself a
    bundle root, the one place `okf_version` is allowed. The generated table under the
    bullets is the same state again for the readers that already parse it.

    Both artifacts regenerate from node state alone, so the committed index can
    never silently drift from the ledger: `doctor` fails when a regeneration
    would change either file. Hand-authored prose is never deleted; the first
    generation over a hand-written index moves its whole body under the manual
    section, which every later regeneration preserves verbatim.

    The pair is written and read under the same file lock the evidence store
    beside it already takes. Two sessions regenerating at once, or one reading
    the currency check while the other writes, would otherwise see one artifact
    from each regeneration and report an index that is only cosmetically behind
    as a workspace breakage.

    A regeneration that finds no nodes at all is refused rather than written,
    since a workspace whose index carries rows never legitimately empties in one
    step, and the empty read is a misconfigured blueprints root every time.
    """

    MARK: ClassVar[str] = (
        "<!-- generated by `atpx index` from node.md state; "
        "regenerate instead of editing anything above the manual section -->"
    )
    MANUAL: ClassVar[str] = "## Manual    (hand-authored, preserved verbatim)"

    def __init__(self, path: Path, *roots: Path, okf_version: str = "") -> None:
        """path: the index markdown file the workspace manifest declares.

        roots: the blueprint roots the nodes were read from, named when a
            regeneration finds none of them and the refusal has to say where it looked.
        okf_version: the Open Knowledge Format version this index is the bundle root of,
            written as its one permitted frontmatter key; no frontmatter at all when empty.
        """
        self.path = path
        self.roots = roots
        self.okf_version = okf_version

    @property
    def graph_path(self) -> Path:
        """The graph JSON artifact, beside the index note."""
        return self.path.with_suffix(".json")

    @cached_property
    def guard(self) -> Guard:
        """The lock both the regeneration and the currency check take, held over both artifacts.

        One lock object per index, so a caller widening the lock around its own read
        of the node set nests inside the regeneration's own acquisition instead of
        waiting on itself. Ensures the index directory on the way, since the lock
        file lives beside the artifacts and a workspace whose index has never been
        generated has nowhere to put it yet.
        """
        self.path.parent.mkdir(parents=True, exist_ok=True)
        return Guard(self.path)

    def bullet(self, node: Node) -> str:
        """One OKF index entry, `* [Title](relative-url) - description`."""
        described = self.described(node)
        link = f"* [{self.titled(node)}]({self.url(node)})"
        return f"{link} - {described}" if described else link

    def claim(self, node: Node) -> str:
        """One node's one-line claim, its `summary` or its statement heading."""
        return node.summary or node.headline

    def described(self, node: Node) -> str:
        """One node's index description: its OKF `description`, else its first sentence."""
        return node.front.description or node.sentence

    def graph(self, nodes: Sequence[Node]) -> dict[str, list[dict[str, str]]]:
        """The blueprint-shaped graph: nodes with slug, root, state, and claim; edges from depends.

        Every row carries the blueprints root the node was found under, so a reader
        with several roots knows which tree a slug lives in and can take this file as
        its roster rather than keeping a second list of its own. An edge naming a slug
        a node has since left resolves to the node of record, so the graph never carries
        an arrow pointing at a name nothing answers to.
        """
        ordered = sorted(nodes, key=lambda node: node.name)
        rows = [
            {
                "slug": node.name,
                "root": node.root,
                "state": self.state(node),
                "claim": self.claim(node),
            }
            for node in ordered
        ]
        aliases = {alias: node.name for alias, node in Aliases(ordered).resolved().items()}
        edges = [
            {"from": node.name, "to": aliases.get(dependency, dependency)}
            for node in ordered
            for dependency in node.front.depends
        ]
        return {"nodes": rows, "edges": edges}

    def preamble(self) -> str:
        """The bundle root's frontmatter, empty unless the workspace declares an OKF version.

        The format gives an index no frontmatter at all, with one exception: the bundle
        root may carry `okf_version` and nothing else, so that is the only key written here.
        """
        return f'---\nokf_version: "{self.okf_version}"\n---' if self.okf_version else ""

    def render(self, nodes: Sequence[Node]) -> str:
        """The full regenerated index text, manual prose preserved.

        The format's own body leads, one section per state with a bullet per node, and
        the generated table follows it for the readers that already parse one. Both
        regenerate from node state alone, so neither can drift from the other.

        nodes: every blueprint node the store tracks.
        """
        title, manual = self.surroundings()
        blocks = [
            self.preamble(),
            f"# {title}",
            self.MARK,
            self.sections(nodes),
            self.table(nodes),
        ]
        if manual:
            blocks.append(f"{self.MANUAL}\n\n{manual}")
        return "\n\n".join(filter(None, blocks)) + "\n"

    def rendered_graph(self, nodes: Sequence[Node]) -> str:
        """The graph JSON artifact's exact text."""
        return json.dumps(self.graph(nodes), indent=2) + "\n"

    def sections(self, nodes: Sequence[Node]) -> str:
        """The OKF body: one `# <state>` section per state, one bullet per node under it.

        Sections order down the certification ladder, so a reader meets what is settled
        before what is still owed, and a state outside the ladder sorts after it under a
        heading of its own.
        """
        grouped: dict[str, list[Node]] = {}
        for node in sorted(nodes, key=lambda node: node.name):
            grouped.setdefault(self.state(node) or _UNSTATED, []).append(node)
        return "\n\n".join(
            f"# {state.replace('_', ' ').capitalize()}\n\n"
            + "\n".join(self.bullet(node) for node in grouped[state])
            for state in sorted(grouped, key=self.__rung)
        )

    def stale(self, nodes: Sequence[Node]) -> list[Path]:
        """The artifacts a regeneration would change, empty when the index is current.

        Read under the write lock, so a concurrent regeneration is never caught
        halfway and a workspace is never called broken over a race it would have
        won a moment later.
        """
        with self.guard:
            expected = {
                self.path: self.render(nodes),
                self.graph_path: self.rendered_graph(nodes),
            }
            return [
                path
                for path, text in expected.items()
                if not path.exists() or path.read_text(encoding="utf-8") != text
            ]

    def state(self, node: Node) -> str:
        """One node's index state: its raw status, or its kind for a statusless special node."""
        special = node.front.category is not Category.CLAIM
        return node.raw_status or (node.front.type or "" if special else "")

    def surroundings(self) -> tuple[str, str]:
        """The (title, manual prose) the regeneration preserves from the existing file.

        A file this generator wrote keeps its title and whatever sits under the
        manual heading. A hand-authored file donates its first `# ` heading as
        the title and its entire remaining body as the manual prose, so the
        first generation moves hand-written sections instead of deleting them.
        Its frontmatter is not part of that body: this generator writes the
        index frontmatter the format allows, so carrying an old block into the
        manual section would leave the file with two.
        """
        if not self.path.exists():
            return self.path.stem, ""
        text = self.path.read_text(encoding="utf-8")
        lines = text.splitlines()
        title = next(
            (line.removeprefix("# ") for line in lines if line.startswith("# ")), self.path.stem
        )
        if self.MARK in text:
            return title, text.partition(self.MANUAL)[2].strip()
        body = [line for line in self.__unfenced(lines) if line != f"# {title}"]
        return title, "\n".join(body).strip()

    def table(self, nodes: Sequence[Node]) -> str:
        """The generated nodes table, one row per node sorted by slug."""
        rows = [
            f"| [[{node.name}]] | {self.__cell(self.state(node))} "
            f"| {self.__cell(self.claim(node))} |"
            for node in sorted(nodes, key=lambda node: node.name)
        ]
        return "\n".join(["| Node | State | Claim |", "| --- | --- | --- |", *rows])

    def titled(self, node: Node) -> str:
        """One node's index title: its OKF `title`, else its slug."""
        return node.front.title or node.name

    def url(self, node: Node) -> str:
        """The link from the index to one node document, relative and POSIX-spelled."""
        return PurePath(os.path.relpath(node.path, self.path.parent)).as_posix()

    def write(self, nodes: Sequence[Node]) -> str:
        """Write both artifacts under the lock, returning the index markdown.

        The pair moves together or not at all, and the render is deterministic given
        a node set, so a second writer under the same lock writes identical bytes
        rather than a mixture of two regenerations.

        nodes: every blueprint node the store tracks.
        """
        with self.guard:
            self.__refuse_blanking(nodes)
            text = self.render(nodes)
            self.path.write_text(text, encoding="utf-8")
            self.graph_path.write_text(self.rendered_graph(nodes), encoding="utf-8")
            return text

    @staticmethod
    def __cell(text: str) -> str:
        """One table cell's text, pipes escaped so a claim can never break the row."""
        return text.replace("|", "\\|")

    @staticmethod
    def __rung(state: str) -> tuple[int, str]:
        """One state's sort key: its rung on the certification ladder, then its own name."""
        ladder = [status.value for status in Status]
        return (ladder.index(state), "") if state in ladder else (len(ladder), state)

    @staticmethod
    def __unfenced(lines: Sequence[str]) -> Sequence[str]:
        """The lines below a leading frontmatter block, all of them when there is none."""
        if not lines or lines[0] != "---":
            return lines
        try:
            return lines[list(lines).index("---", 1) + 1 :]
        except ValueError:
            return lines

    def __carried(self) -> list[str]:
        """The generated node rows the index on disk already holds, none when it has none."""
        if not self.path.exists():
            return []
        return [
            line
            for line in self.path.read_text(encoding="utf-8").splitlines()
            if line.startswith("| [[")
        ]

    def __refuse_blanking(self, nodes: Sequence[Node]) -> None:
        """Refuse a regeneration that found nothing over an index that carries rows.

        What this catches, from the field: a `blueprints` setting read back as the text
        of a list matched no directory, the store answered with an empty graph, and the
        regeneration replaced a 63-row index with an empty table under a lock that made
        it look deliberate. A populated workspace never empties in one step, so an empty
        read is a root that does not exist, and the roots are what the message has to
        name because the setting behind them is the thing to fix.

        nodes: the node set this regeneration would write.
        """
        if nodes or not (carried := self.__carried()):
            return
        roots = ", ".join(root.as_posix() for root in self.roots) or "none declared"
        raise BlankIndexError(
            f"regenerating {self.path} found no nodes while the index on disk carries "
            f"{len(carried)}, so the blueprint roots searched are wrong rather than "
            f"empty and nothing was written. Roots searched: {roots}. Check that "
            "[workspace] blueprints names directories that exist."
        )
