from .audit import witnesses


class LabAudit:
    """The lab gate: at least one printed trial receipt, every trial through its gates.

    The seam between a claim and an experiment framework. A claim command that drives
    mainboard trials prints one `mainboard_receipt` JSON line per trial, carrying the
    trial's content-addressed `run_id`, its `outcome`, and every declared gate's verdict.
    Auditing those lines is what makes a claim's certificate say which experiment run
    produced it rather than only that some command exited zero, and re-verifying a claim
    stays one `check` away because the receipt is regenerated by the same command.

    A trial the framework withheld (a gate legitimately not ready) fails the gate here
    just as a broken one does: either way the claim was not checked, and the violation
    line carries the framework's own reason so a reader can tell the two apart.
    """

    rigor = "lab"
    key = "mainboard_receipt"

    def violation(self, output: str) -> str:
        """Why the output does not earn lab rigor, empty when it does."""
        lines = witnesses(output, key=self.key)
        if not lines:
            return f"no {self.key} line printed"
        withheld = [
            f"{line.get('run_id')} {line.get('outcome')} ({line.get('reason')})"
            for line in lines
            if line.get("outcome") != "passed"
        ]
        if withheld:
            return f"trials did not clear their gates: {', '.join(withheld)}"
        return ""
